# -*- coding: utf-8 -*-
"""ASSIGNMENT-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxTsfjzh2joUUeWAq6oSzCFH9gnOMGem

ADDITION PROGRAM
"""

a=2
b=2
print('the sum of two numbers is' ,a+b)

"""SUBTRACTION PROGRAM"""

a=5
b=2
print('the difference of two numbers is ',a-b)

"""MULTIPLICATION PROGRAM"""

a=3
b=12
print('the product of two numbers is',a*b)

"""DIVISION PROGRAM"""

a=20
b=5 
print('the division of two numers is',a/b)

"""MODULUS"""

a=10
b=3
print(a%b)

"""EXPONENT"""

a=3
b=2
print(a**b)

"""FLOOR DIVISION"""

a=3
b=2
print(a//b)

"""Program to calculate simple **interest**"""

P = float(input("Enter the principal amount : "))
N = float(input("Enter the number of years : "))
R = float(input("Enter the rate of interest : "))
SI = (P * N * R)/100
print("Simple interest :",SI)

"""Program to find Area Of **Circle**"""

PI = 3.14
radius = float(input(' Please Enter the radius of a circle: '))
area = PI * radius * radius
print(" Area Of a Circle = ",area)

"""Program to calculate area of triangle"""

a = float(input('Enter base of the triangle: '))
b = float(input('Enter height of triangle: '))
area = 0.5*(a)*(b)
print('The area of the triangle is ',area)

"""Program to convert temperature in celsius to fahrenheit"""

c =float(input('enter celcius temperature'))
fahrenheit = (c* 1.8) + 32
print('temperature in fahrenheit is',fahrenheit)

"""Program to calculate area of rectangle"""

length = float(input('Please Enter the Length of a Triangle: '))
width = float(input('Please Enter the Width of a Triangle: '))
area = length*width
print("The Area of a Rectangle is ", area)

"""Program to find Perimeter of Square"""

s=int(input("Side : "))
perimeter=4*s
print("Perimeter of Rectangle : ",perimeter)

"""Program to find circumferance of circle"""

PI = 3.14
radius = float(input(' Please Enter the radius of a circle: '))
circumference = 2 * PI * radius
print("Circumference of the circle is : " , circumference)